galaxy_info:
  role_name: docker_ce
  author: Bjorn Oscarsson
  company: none
  description: "Installs and configures Docker Community Edition (CE)"
  min_ansible_version: 2.8
  license: MIT
  platforms:
  - name: Fedora
    versions:
      - 30
      - 31

  - name: EL
    versions:
      - 7
      - 8

  - name: Debian
    versions:
      - stretch
      - buster

  - name: Ubuntu
    versions:
      - xenial
      - bionic
      - focal

  galaxy_tags:
    - docker
    - containers
    - virtualization
    - compose
    - orchestration
    - system

dependencies: []
