---
- name: Push latest {{docker_build_image_name}}
  run_once: true
  shell:
    _raw_params: "docker push {{ docker_build_image_name }}:latest"
  delegate_to: localhost
  when:
  - image_exists.stdout == "0" and build_and_push_tag_latest == true and build_and_push_push == true

- name: Push version {{docker_build_image_name}}
  run_once: true
  shell:
    _raw_params: "docker push {{ docker_build_image_name }}:{{ docker_build_image_tag }}"
  delegate_to: localhost
  when:
  - image_exists.stdout == "0" and build_and_push_push == true

- name: Push versions {{docker_build_image_name}}
  run_once: true
  shell:
    _raw_params: "docker push {{ docker_build_image_name }}:{{ item }}"
  delegate_to: localhost
  with_items:
  - "{{ docker_build_image_tag.split('.')[0] }}.{{ docker_build_image_tag.split('.')[1] }}"
  - "{{ docker_build_image_tag.split('.')[0] }}"
  when: image_exists.stdout == "0" and build_and_push_tag_versions == true and build_and_push_push == true and
        docker_build_image_tag.split('.')|length > 1
