---
# tasks file for sgi_gtech_ship_files
- name: set full path
  set_fact:
    repository_full_path: "{{nfs_share_source_files_root}}/{{game_files_path}}/{{ship_number}}/"
- name: retrieve from share
  block:
    - name: 
      debug:
        var: repository_full_path

    - name: retrieve file_ship_code
      find:
        paths:
          - "{{repository_full_path}}"
        patterns:
          - "VALB*.ILS"
      register: info

    - name: set var file_ship_code
      set_fact:
        file_ship_code: "{{ info.files.0.path.split('VALB')[1].split('.')[0] }}"

    - name: Fail if empty repository folder
      fail:
        msg: "Non ci sono file nella cartella {{ repository_full_path }} !"
      when:
        - info.matched is defined
        - info.examined|int >= 1
        - info.matched|int == 0
  delegate_to: localhost

- name: take file from Windows share
  copy:
    src: "{{repository_full_path}}/{{item}}"
    dest: /tmp/
  with_items:
    - "SHIP{{file_ship_code}}.ILS"
    - "VALB{{file_ship_code}}.ILX"
    - "VALB{{file_ship_code}}.ILS"
    - "PRIZE_DATA_{{file_ship_code}}.ILS"

- name: dos2unix file
  shell: dos2unix /tmp/*{{file_ship_code}}*
  
- name: Ensure VALB files has equal dimensions Step 1
  stat: 
    path: /tmp/VALB{{file_ship_code}}.ILX
  register: ilx

- name: Ensure VALB files has equal dimensions Step 2
  stat: 
    path: /tmp/VALB{{file_ship_code}}.ILS
  register: ils

- name: trasfer VALB* to SGI directory
  become: true
  become_user: sgimgr
  become_method: su
  copy:
    src: /tmp/{{ item }}
    dest: /home/sgimgr/VALB/
    remote_src: yes
  with_items:
    - "SHIP{{file_ship_code}}.ILS"
    - "VALB{{file_ship_code}}.ILX"
    - "VALB{{file_ship_code}}.ILS"
  when: ilx.stat.size == ils.stat.size

- name: trasfer PRIZE_DATA* to SGI directory
  become: true
  become_user: sgimgr
  become_method: su
  copy:
    src: /tmp/{{ item }}
    dest: /home/sgimgr/PRIZE_DATA/
    remote_src: yes
  with_items:
    - "PRIZE_DATA_{{file_ship_code}}.ILS"
  when: ilx.stat.size == ils.stat.size

- name: clean files
  file:
    path: /tmp/{{ item }}
    state: absent
  with_items:
    - "SHIP{{file_ship_code}}.ILS"
    - "VALB{{file_ship_code}}.ILX"
    - "VALB{{file_ship_code}}.ILS"
    - "PRIZE_DATA_{{file_ship_code}}.ILS"