---
dockerhub_base: ansible
dockerhub_version: 9.3.0
#dockerhub_version: 18.0.0
awx_task_hostname: awx
awx_web_hostname: awxweb
postgres_data_dir: /var/lib/postgres_awx
host_port: 8052
docker_compose_dir: "{{ docker_compose_project_path__awx }}"
pg_username: awx
pg_password: "{{ awx_installer_vars_pg_password }}"
pg_admin_password: "{{ awx_installer_vars_pg_admin_password }}"
pg_database: awx
pg_port: 5432
rabbitmq_password: "{{ awx_installer_vars_rabbitmq_password }}"
rabbitmq_erlang_cookie: cookiemonster
admin_user: "{{ awx_installer_vars_admin_user }}"
admin_password: "{{ awx_installer_vars_admin_password }}"
secret_key: "{{ awx_installer_vars_secret_key }}"
# http_proxy: {{ http_proxy }}
# https_proxy: {{ http_proxy }}
# no_proxy: {{ http_no_proxy }}
# awx_container_search_domains: sidi.mpi.it,mpi.it,trampi.it,istruzione.it
# awx_alternate_dns_servers: "172.16.190.141"
project_data_dir: "{{ docker_compose_dir }}/projects"
rilasci_data_dir: /mnt/rilasci
ansible_project_root_path: "{{ '/var/lib/awx/projects/_28__ansible_gev' if tower_job_id is defined else (inventory_file|dirname|dirname) }}"