---
- name: "Setup Delivery nuovi server"
  hosts: "{{ hostlist | default('null') }}"
  become: true
  vars:
    ansible_gev_default_pass: k89bBBpN2nX2ND
    administrator_default_password: C4mb14m1!
    ansible_gev_default_username: ansible_gev
    ansible_project_root_path: "{{ '/var/lib/awx/projects/_28__ansible_gev' if tower_job_id is defined else (inventory_file|dirname|dirname|dirname) }}"
    centrify_zone_name: "{{ centrify_zone | default('null') }}"
  vars_prompt:
    - name: ad_user
      prompt: Username AD lottomatica.net
      private: no
    - name: ad_pass
      prompt: Password AD lottomatica.net

  tasks:
    - name: set fact ENV 
      set_fact:
        env_igt: "{{ ansible_hostname.split('-')[0] }}"
        group_igt: "{{ ansible_hostname.split('-')[1] }}"

    - name: PREREQUISITI - Test Connection
      ping:

    - name: PREREQUISITI - Serivces is enabled
      ansible.builtin.service:
        name: "{{ item }}"
        enabled: yes
      with_items:
        - "sshd"

    - name: PREREQUISITI - Add the user {{ ansible_gev_default_username }}
      user:
        name: "{{ ansible_gev_default_username }}"
        comment: Ansible GEV Automation User
        uid: 266874
        group: wheel
        password: "{{ ansible_gev_default_pass }}"

    - name: PREREQUISITI - Aggiunta utente nel sudoers
      copy: 
        dest: /etc/sudoers.d/ansible_gev 
        content: |
          ansible_gev ALL=(ALL) NOPASSWD:ALL
        owner: root
        group:  root
        mode: '0400'
        validate: 'visudo -cf %s'

    - name: PREREQUISITI - Create .ssh directory 
      file:
        path: /home/{{ ansible_gev_default_username }}/.ssh
        state: directory
        mode: '0700'
        owner: "{{ ansible_gev_default_username }}"
        group: wheel

    - name: PREREQUISITI - Check raggiungibilità qradar-cassaforte-centrify
      debug: 
        msg: da implementare

    - name: PREREQUISITI - Copy ssh pub key in to ansible user
      copy: 
        src: "{{ ansible_project_root_path }}/files/mgmt/id_rsa.pub"
        dest: /home/{{ ansible_gev_default_username }}/.ssh/authorized_keys
        owner: "{{ ansible_gev_default_username }}"
        group: wheel
        mode: '0600'

    - name: PREREQUISITI - Update sshd config for access only domain users
      blockinfile:
        path: /etc/ssh/sshd_config
        marker: "# {mark} ANSIBLE MANAGED BLOCK "
        insertafter: EOF
        block: |
          AllowGroups oper taddm batch administrator ansible_gev
          Match User spp_svc
          PasswordAuthentication no
        backup: yes
        validate: /usr/sbin/sshd -T -f %s
      notify:
      - Restart SSHD
      when: env_igt == "RP"

    - name: CENTRIFY - Check if CentrifyDC is installed
      yum:
        list: 'CentrifyDC'
      register: yum_cmd
      when: env_igt == "RP"

    - name: CENTRIFY - Check if computer is joined to domain
      command: adinfo
      register: adinfo_cmd
      changed_when: adinfo_cmd.rc == 10
      failed_when:
      - adinfo_cmd.rc != 10
      - adinfo_cmd.rc != 0
      when: env_igt == "RP"

    - name: CENTRIFY - Join computer to Active Directory
      block:
      - name: CENTRIFY - Join the computer to Active Directory domain using self-service
        command: adjoin lottomatica.net --zone {{ centrify_zone_name }} --container "lottomatica.net/Centrify" --name {{ ansible_hostname }} --user {{ ad_user }}@lottomatica.net -p {{ ad_pass }} 
      when:
      - yum_cmd.results | selectattr("yumstate", "match", "installed") | list | length == 1
      - adinfo_cmd.rc == 10
      when: env_igt == "RP"
      
    - name: CASSAFORTE ELETTRONICA - Create .ssh directory 
      file:
        path: /home/spp_svc/.ssh
        state: directory
        mode: '0700'
        owner: spp_svc
        group: oper

    - name: CASSAFORTE ELETTRONICA - Copy ssh pub key in to service user
      copy: 
        dest: /home/spp_svc/.ssh/authorized_keys
        content: |
          ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCtlM2Bcw5nzaqFWNwvEgETgUu5Q1SXARvCcx7q3+9n7sdFyQofpEfdPlpGQFbp0g5zVDUc/vsPiTS1vTxHOZ/QWgVC9C17rUg97nGNYvmK+YueXQHIww/0kMaYL0/rtKTbvV5FTpn7moZ+qr+bXlVodZXLye52JPg9YD9jGZtb/g1AgC2Ry/MIc7Oixr7RjnAyzKA/j3w20VoQIItuL+ZkrfqIkhRBhtWTZ21rrkQrYgQS6FdqLT+WI/wOSW2IgVBYO1D+NH8AL5aYWzYvxVseVU+Huspb95ZhSu/KeBCZfbnjAPfjQXHDiaLUOr1UJbjJvXTR1/0VyDaxoOs+CJvu0B1pqg3rnJxmfKRXUVESVqFrkqBtzXaMcC7QDF5dfzjW8UUj68nHXpgUh/J5oJ7bVQKNF69axixAkBVJAECIjgzMXlESi8g5/q9WOjtHsdVt2okYsWeManteG12+ozbzQDvfdMmJ8Y5mcJDEhoT2L+ilMMrTtRmDMeeqwftWTnwBjZ/w+xjwcvzzIKsuH/0xWU69LgWk1X9HcWSVHyYhqdX4H38605nGCf8lxd8I4SnytJ8y5JGh9u89SvbeLHV6DTbyZYj9sCLsK8aFXuEQf0OayfMiIc7wM40o4QQqoGkzDD9Lgh/wxvLseBSuuQbFqzMfOdp3uRR4u8oYA1C9LQ== root@LXRP-PANDIS-AS4
        owner: spp_svc
        group:  oper
        mode: '0600'

    - name: CASSAFORTE ELETTRONICA - Aggiunta utente nel sudoers
      copy: 
        dest: /etc/sudoers.d/spp_svc 
        content: |
          spp_svc ALL=(root) NOPASSWD: /usr/bin/passwd,/bin/grep,/bin/egrep
        owner: root
        group:  root
        mode: '0400'

    - name: CASSAFORTE ELETTRONICA - Fetch info from server step 1
      shell: "grep MNGT /etc/sysconfig/network-scripts/* |  awk -F ':' '{print $2}' | awk -F '=' '{print $2}' | awk -F '-' '{print $1}'"
      register: mgnt_network_iface

    - name: CASSAFORTE ELETTRONICA - Fetch info from server step 2
      shell: "grep IPADDR /etc/sysconfig/network-scripts/ifcfg-{{ mgnt_network_iface.stdout }} | awk -F '=' '{print $2}'"
      register: mgnt_network_ipaddr

    - name: CASSAFORTE ELETTRONICA - create CSV file headers
      copy:
        dest: "{{ ansible_project_root_path }}/files/securevault/securevault_{{ group_igt }}.csv"
        content: |
          Name,NetworkAddress,PlatformId,EffectiveProfileId,AssetPartionName,ConnectionProperties.ServiceAccountCredentialType,ConnectionProperties.ServiceAccountSshKeyId,ConnectionProperties.EffectiveServiceAccountName,ConnectionProperties.ServiceAccountName,AssetPartitionId,ConnectionProperties.PrivilegeElevationCommand,AccountDiscoveryScheduleId,PlatformDisplayName,ConnectionProperties.ServiceAccountSshKeyFingerprint,ConnectionProperties.ServiceAccountProfileName,ConnectionProperties.ServiceAccountProfileId
      run_once: true
      delegate_to: localhost
      become: false

    - name: CASSAFORTE ELETTRONICA - create CSV file 
      copy:
        dest: "{{ ansible_project_root_path }}/files/securevault/securevault_{{ group_igt }}.csv"
        content: |
          {{ ansible_hostname }},{{ mgnt_network_ipaddr.stdout }},183,13,CA Digital,SshKey,1406456083,spp_svc,spp_svc,12,sudo,71,Red Hat Enterprise Linux (RHEL) Other,88F1A8CF440FC13D5801D2DB50E0443E,CA DIGITAL NO PWD CHANGE,26
      delegate_to: localhost
      become: false


  handlers:
    - name: Restart SSHD
      service:
        name: sshd
        state: restarted
